[project]
name = "veritas-corrective-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "ddg>=0.2.2",
    "ddgs>=9.14.4",
    "fastapi>=0.140.13",
    "grok>=6.2",
    "groq>=1.6.0",
    "ipykernel>=7.3.0",
    "langchain-text-splitters>=1.1.2",
    "langgraph>=1.2.10",
    "ollama>=0.6.2",
    "pymupdf>=1.28.0",
    "pymupdf4llm>=1.28.0",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.6.1",
    "streamlit>=1.60.0",
    "tiktoken>=0.13.0",
    "uvicorn>=0.51.0",
]
